numeroUm = float (input('Escreva o primeiro número: '))
numeroDois = float (input('Escreva o segundo número: '))
media = ((numeroUm*4 + numeroDois*0.61)/2)
print ('A Soma do primeiro número é: ', (int((numeroUm * 4))))
print ('A Soma do segundo número é: ',(int((numeroDois * 0.6))))
print  ('A média aritimética é: ', (int(media)))